### ISSUE TITLE
A small question regarding the DNF search algorithm in the paper

### ISSUE THREAD

**Issue by csimplestring** [brg-liuwei/godnf#9]
Hey, glad to know you've done such a good job for implementing this algorithm for that paper.

When I read the paper, in the Complexity section at page 6, the author says: `The sorting in Step 14 takes O(log(|S|)) because the inverted list is initially sorted, and we only need to bubble down one posting list in PLists using a heap for each posting list skipped. ` But I did not find a 'heap' is used to sort the posting lists in this implementation, could you please help me clarify this? 

Thanks!

**Comment by brg-liuwei** [comment]
@csimplestring Hi, as your email nickname is "wangyi", I suppose you can read Chinese. For saving time, I will answer your question by Chinese as follows. And feel free to tell me if you cannot understand Chinese, I’ll give you an English version.

你好，刚才我查了一下论文，你提到的用堆(heap)去把算法复杂度降为O(log(|S|))的部分，我的代码中确实没有实现。其中主要的原因还是因为写起来比较麻烦，所以我就直接用线型搜索了。因为当时我做这个工作的时候，我认为这个算法主要的优点在于把第一层剪枝，即对于一个有t个条件的assignment，可以把所有大于t个BE的conjunction给剪掉。可能是由于我的公司业务规模远小于雅虎这样的量级，目前的这个实现已经完全能满足工程上需求，所以我之后也就没有再去对这个算法内部的细节进行优化。

我想，你问这个问题，也许是想找到具体的代码或者例子搞明白作者的这段话是怎么实现的，毕竟作者在这里也就提了一句，在论文中没有具体讲该怎么做。其实如果你熟悉堆排序算法的话，你可以理解为堆排序里面的每一个节点，对应的都是一条plist中的一个节点。在搜索过程中，把堆顶plist的当前节点朝后移动一步，相当于堆排序过程中堆顶元素变化了，于是要重新调整堆，调整堆的复杂度是O(logN)。下面是个示意图：

1，假设有5条PLists，需要检索的assignment有3个条件。我们对每个plist都有一个指针指向当前节点，把当前节点构成一个堆(小括号表示当前节点的指针)：

                            P[0]:   (1)-4-6
                                      /     \
                   P[1]: (2)-3        P[2]: (5)-6-7
                           /    \
          P[3]:  (3)    P[4]: (3)-5  

2，现在你把堆顶的Plist的指针朝后移动一位(就是论文中所说的skipToNextID，由于plist里面的ID是有序的，所以可以用二分的方法一次朝后skip多个，这里我为了表述方便就朝后移动一位)：

                         P[0]:   1-(4)-6
                                      /     \
                                (2)-3    (5)-6-7
                               /    \
                            (3)   (3)-5

3，现在堆顶是4，所以要调整堆，把4和左儿子P[1]交换，发现4仍然比两个子节点(3)大，再把4下沉到右儿子，形成下图，即完成排序：

                       P[1]:     (2)-3
                                   /    \
                P[4]:  (3)-5   P[2] (5)-6-7
                          /    \
            p[3]: (3)  p[0]: 1-(4)-6

4，接下来的搜索过程是移动P[1]的指针，指向(3)，然后发现前三个PList的指针都是指向(3)，所以编号为(3)的conjunction可能是检索目标。

以上就是我对这个过程的理解。具体实现的话，要注意到多次检索和并发检索的情况，每一次检索需要用指针去维护各个plist的相对位置，而不能去实际移动plist。代码实现起来具有一定的复杂性。

这是我好几年前的一点微不足道的工作，今天突然被人翻出来，非常意外，幸蒙垂询，希望我的回答能对你有所帮助。另外非常欢迎你针对这个issue提交pr。

**Comment by brg-liuwei** [comment]
哦，上面用文本编辑堆示意图因为排版问题歪了，我截个图贴这里好方便看：

![](https://user-images.githubusercontent.com/5916447/109591670-e5e84b80-7b48-11eb-8bc6-c980d162a0ef.jpeg)

**Comment by csimplestring** [comment]
@brg-liuwei  原来是同行啊，幸会幸会。多谢回复，这个问题确实是困扰我，论文就说了一句用heap，但是heap的操作维护很麻烦。Go标准库的heap其实用起来很不方便: 因为论文中的算法直接用下标来访问pLists，但是如果pLists是heap结构，就无法用下标直接访问，必须不断地pop操作来获取下一个元素，这也是我觉得不够直观的地方：如果用heap来存储pLists，那完全就不需要Step-14那一行的sortByCurrentEntry了，因为调用一个plist的skipTo之后，我可以直接先pop再push，这样heap就直接被调整重排序了，进入下一个while循环的时候，pLists就已经是排好序的了。

 我搜了github上关于那篇论文的实现，发现都只是实现了DNF的算法，论文中CNF的算法没有实现，请教一下是不是有什么特殊的考虑？

**Comment by brg-liuwei** [comment]
@csimplestring 同学好，这几天我公司事情有点多，没有及时回复，先道一声抱歉。

先说一下这里heap的问题。上文我的答复中提了一下，pList本身是不能放在堆里面的，因为pList是”静止“的，就如同经典的倒排索引一样，这个数据结构应该是只读的，否则不能承受并发的检索(如果加锁的话，特别麻烦，而且效率极低)，就没有使用的意义了。所以类似地思考一个简化的问题：如果给你一个数组，要求不能对数组进行改变，那怎么对数组排序？答案就是另外开一个索引数组，这个索引数组的每个元素的值用于原数组的下标，直接对下标进行排序。因此，这里的heap其实是一个指针数组，数组里面的每个元素指向每一条pList。在每一次检索的时候，都需要***构建一个新的指针数组***，建立heap，中间过程就是不断的对heap进行调整，这完全是可以用go标准库的heap来实现的。

关于为何只实现了DNF而没有实现CNF的问题，我认为有两个原因。第一个是因为在日常的广告需求中，大多数广告的投放条件都是”与“而不是”或“，所以如果用DNF，广告投放条件就是一个conjunction。而如果用CNF，在逻辑上就要拆成多个”与“单元的组合。所以在实际工程应用中，可能DNF更实用一些。第二个原因嘛，这个DNF算法当时是《计算广告》的作者刘鹏老师告诉我的，后来我看他出的书，书里面讨论布尔表达式的部分就只提到了DNF。所以我估计你搜到的其他实现的作者大都是从《计算广告》这本书上看到的。至于为什么这本书在广告布尔检索部分只提了DNF，没有提CNF，这就不得而知了，下次有机会见到他的话我帮你问问 :)

**Comment by csimplestring** [comment]
@brg-liuwei  谢谢回复，只实现了DNF而没有实现CNF的原因确实跟我想的一样，一般的广告投放的audience targeting的条件确实只用DNF就好了。
